### ISSUE TITLE
Verify Transaction

### ISSUE THREAD

**Issue by SirG97** [NextmediaMa/youcan-payment-php-sdk#17]
After payment has been completed and the user is redirected back to either the success or error URL on the  merchant website with the transaction ID and other info about the transaction. This response is sent via a get request. Is there a way to verify that the reponse sent to the callback URL is coming from YouCan Pay servers??

Is there an API endpoint for independently verifying if a transaction is successful or vice versa?

**Comment by SirG97** [comment]
I have seen something useful in the docs though it is not very clear
`
// get details of a transaction
$transaction = $youCanPay->transaction->get('transaction-id');
var_dump($transaction->getAmount(), $transaction->getCurrency());`

[https://youcanpay.com/docs#sandbox_backend_integration](https://youcanpay.com/docs#sandbox_backend_integration)

**Comment by Whyounes** [comment]
Never rely on the callback, it can be faked by malicious users. Make sure to rely on the webhook notification to do the actual processing needed after the payment.

**Comment by SirG97** [comment]
Thanks.. I know. I later used the webhook.

I'm regretting it though. The person I integrated the payment sdk for
refused to pay me for the work and even went ahead to block me and every
access I had. I wish I had left it that way so that he will be dealt with
and then he'll run back to complain.
