### ISSUE TITLE
CSS missing in the 3dsecure modal 

### ISSUE THREAD

**Issue by iamrachid** [NextmediaMa/youcan-payment-php-sdk#22]
![Screenshot from 2022-06-28 13-42-39](https://user-images.githubusercontent.com/25393908/176183343-cd67a1b9-eff8-410e-997e-d8682da90a31.png)

```html
<div id="ycp-3ds-modal">
     <style>[Promise Object]</style>
</div>
```

due to a promise not awaited in [ycpay.js](https://youcanpay.com/js/ycpay.js?ver=2.0.9)
```javascript
rn = Promise.resolve().then((function () {
     return ii
}));
```

**Comment by azuradarius** [comment]
Should be good now, thank you for reporting the issue.
