### ISSUE TITLE
error when i use sandbox mode

### ISSUE THREAD

**Issue by aizen991** [NextmediaMa/youcan-payment-php-sdk#23]
During rendering credit card form in sandbox mode i get this error message :Cannot read properties of undefined (reading 'payments_active').
I made live  transaction  by my credit card in the live mode it works fine 
note: sandbox mode activated in youcan dashboard, i use public sandbox key for frontend code, public and private sandbox key for backend.

const ycPay = new YCPay('pub_sandbox_xxxxxxx',
      {
        isSandbox:true,
        formContainer: '#payment-container',
        locale: 'en',
        errorContainer: '#error-container'
      });
    ycPay.renderCreditCardForm();
</script>

**Comment by ubaidismail** [comment]
Facing same error! 
` (reading 'payments_active').`

**Comment by ubaidismail** [comment]
@aizen991 Did you found anything regarding the error?

**Comment by aizen991** [comment]
@ubaidismail It's looks like a Sdk bug , the sandbox works fine on phone mobile navigator  but on PC doesn't, for me i tested my integration from phone, i can see test transaction on Youcan dashboard and the Webhook called correctly,

**Comment by Whyounes** [comment]
Thank you for reporting this guys, will be fixed as soon as possible

**Comment by azuradarius** [comment]
Issue fixed, thank you for reporting.

**Comment by aizen991** [comment]
thank you , it's fixed
